Repository openscilab/ipspot, pull requests merged in 2025-05, with the labels that each got.

#17 Tests Modification
  ipspot/functions.py
  tests/test_functions.py
  tests/test_ipv4.py
Labels: test

#18 Version 0.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  ipspot/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#23 Private IPv4 Modification
  CHANGELOG.md
  ipspot/functions.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: bug, test

#24 `is_ipv4`
  CHANGELOG.md
  ipspot/__init__.py
  ipspot/functions.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: enhancement

#25 `is_loopback`
  CHANGELOG.md
  ipspot/__init__.py
  ipspot/functions.py
  tests/test_ipv4.py
Labels: enhancement

#26 New API: `tnedime` (tnedi.me)
  CHANGELOG.md
  README.md
  ipspot/functions.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: enhancement, ipv4 api

#27 `IPSB` API fix
  CHANGELOG.md
  ipspot/functions.py
  tests/test_ipv4.py
Labels: bug, ipv4 api, test

#28 IPv4 HTTP Adapter
  CHANGELOG.md
  ipspot/functions.py
  tests/test_ipv4.py
Labels: enhancement

#29 Refactor
  ipspot/functions.py
  tests/test_ipv4.py
Labels: refactoring

#30 Refactor
  .coveragerc
  CHANGELOG.md
  ipspot/__init__.py
  ipspot/__main__.py
  ipspot/cli.py
  ipspot/ipv4.py
  ipspot/utils.py
  setup.py
  tests/test_utils.py
Labels: refactoring

#31 IPv4 `AUTO` mode
  CHANGELOG.md
  ipspot/ipv4.py
Labels: enhancement

#32 Version 0.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  ipspot/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#38 ipapi.co
  CHANGELOG.md
  README.md
  ipspot/ipv4.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: enhancement, ipv4 api

#39 Names
  CHANGELOG.md
  README.md
  ipspot/ipv4.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: refactoring

#41 New API `my-ip.io`
  CHANGELOG.md
  README.md
  ipspot/ipv4.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: ipv4 api

#42 Refactor
  CHANGELOG.md
  ipspot/ipv4.py
  ipspot/params.py
Labels: refactoring

#43 New API `ifconfig.co`
  CHANGELOG.md
  README.md
  ipspot/ipv4.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: ipv4 api

#44 Auto-Safe Mode
  CHANGELOG.md
  README.md
  ipspot/cli.py
  ipspot/ipv4.py
  ipspot/params.py
  tests/test_ipv4.py
Labels: enhancement

#46 Refactor
  CHANGELOG.md
  ipspot/ipv4.py
Labels: refactoring
