Repository openscilab/ipspot, pull requests merged in 2025-04, with the labels that each got.

#11 Discord Badge Added
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.md
  README.md
Labels: documentation

#12 ip.sb
  CHANGELOG.md
  README.md
  ipspot/functions.py
  ipspot/params.py
Labels: enhancement, ipv4 api

#13 `--timeout` parameter added
  CHANGELOG.md
  README.md
  ipspot/functions.py
Labels: enhancement

#14 Header
  .github/workflows/test.yml
  CHANGELOG.md
  ipspot/functions.py
  ipspot/params.py
Labels: enhancement

#15 Code Quality
  README.md
Labels: documentation
